// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaApi.Models;

#nullable disable

namespace PizzaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("PizzaApi.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DoughType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSpicy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 0,
                            DoughType = 0,
                            Image = "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=500&auto=format&fit=crop",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Price = 395,
                            Text = "Соковите курча, моцарела, сири чеддер і пармезан, вершковий соус, томати, соус альфредо, часник",
                            Title = "Сирне курча"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 0,
                            DoughType = 0,
                            Image = "https://images.unsplash.com/photo-1628840042765-356cda07504e?q=80&w=500&auto=format&fit=crop",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Price = 449,
                            Text = "Гостра ковбаса чоризо, гострий перець халапеньо, соус барбекю, мітболи, томати, солодкий перець, червона цибуля, моцарела",
                            Title = "Діабло"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 0,
                            DoughType = 0,
                            Image = "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?q=80&w=500&auto=format&fit=crop",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Price = 399,
                            Text = "М'ясний соус болоньєзе, соус бургер, солоні огірочки, томати, червона цибуля, моцарела",
                            Title = "Чізбургер-піца"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 0,
                            DoughType = 0,
                            Image = "https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?q=80&w=500&auto=format&fit=crop",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Price = 250,
                            Text = "Класична піца з великою кількістю моцарели, фірмовим томатним соусом та італійськими травами",
                            Title = "Маргарита"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 0,
                            DoughType = 0,
                            Image = "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?q=80&w=500&auto=format&fit=crop",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Price = 350,
                            Text = "Пікантні ковбаски пепероні, багато сиру моцарела та класичний томатний соус",
                            Title = "Пепероні"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 0,
                            DoughType = 0,
                            Image = "https://images.unsplash.com/photo-1571066811602-71683a3f680d?q=80&w=500&auto=format&fit=crop",
                            IsSpicy = false,
                            IsVegetarian = false,
                            Price = 290,
                            Text = "Солодкий перець, томати, червона цибуля, маслини, свіжі печериці та сир моцарела",
                            Title = "Вегетаріанська"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
